export const periods = [
  { name: "平安時代中期", displayOrder: 1 },
  { name: "平安時代後期", displayOrder: 2 },
  { name: "鎌倉時代前期", displayOrder: 3 },
  { name: "鎌倉時代中期", displayOrder: 4 },
  { name: "鎌倉時代後期", displayOrder: 5 },
  { name: "南北朝時代", displayOrder: 6 },
  { name: "室町時代前期", displayOrder: 7 },
  { name: "室町時代中期", displayOrder: 8 },
  { name: "室町時代後期", displayOrder: 9 },
  { name: "江戸時代前期", displayOrder: 10 },
  { name: "江戸時代中期", displayOrder: 11 },
  { name: "江戸時代後期", displayOrder: 12 },
  { name: "明治時代", displayOrder: 13 },
  { name: "現代", displayOrder: 14 },
];
