import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/header";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s", // 各ページのタイトルが %s に入る
    default: "Great App", // 個別設定がないページのデフォルト
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased", // geist-sansは下のvariableで適用されるため修正
          geistSans.variable,
          geistMono.variable,
          // 背景色と全体レイアウトの設定
          "bg-linear-to-t from-neutral-300 via-neutral-200 to-neutral-100",
          "flex min-h-screen flex-col",
        )}
      >
        <Header /> {/* ここにヘッダーを追加 */}
        {/* メインコンテンツ: justify-centerで中央寄せを維持しつつ、ヘッダーの高さ分下げる */}
        <main className="flex flex-1 flex-col pt-20 pb-10 px-4 w-full max-w-7xl mx-auto">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
